site_name: John Lawson | Leader of Doers
site_url: 'https://git.rockfin.com/pages/jlawsonb/portfolio'
site_description: 'Portfolio and resume for a Leader of talented people'
site_author:      'jlawsonb@gmail.com'

plugins:
    - search
    - table-reader
    - awesome-pages

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde

theme: 
  name: windmill

nav:
  - Portfolio Summary: index.md
  - Resume: Resume/index.md
  - Projects: Projects/index.md
  - Speaking: Speaking/index.md

extra:
  repo_icon: 'github'
  approved_standards: 34
  current_version: 0.0.10